# Keras Pytorch etc.

In [209]:
import numpy as np
import tensorflow as tf

from numpy import array
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

In [243]:
# A Simple Network with One Node weights

model = tf.keras.Sequential()
model.add(Dense(1, activation='sigmoid', input_dim=1))
opt=tf.keras.optimizers.SGD(learning_rate=1, momentum=0.0, nesterov=False)
model.compile(optimizer=opt, loss='binary_crossentropy')

# ~~~ Set custom weights
wts1=( np.array([[1]]),  np.array([0]) )
print('Weights(1):' , wts1[0].shape, wts1[0] )
model.layers[0].set_weights(wts1)
wts11=model.layers[0].get_weights()
print('Weights:' , wts11[0].shape, wts11[1].shape, wts11[0], wts11[1] )

#--- Do one pass through NN
data=np.array([[1]]).reshape(1,-1)
y = np.array([1])

yhat = model.predict(data, verbose=0)
print("Before Fit: " , yhat)

f = model.fit(data, y, epochs=1, verbose=1)

print("#--- Weights after one pass");
wts1=model.layers[0].get_weights()
print('Weights:' , wts1[0].shape, wts1[0] )

op=model.layers[0].output


Weights(1): (1, 1) [[1]]
Weights: (1, 1) (1,) [[1.]] [0.]
Before Fit:  [[0.7310586]]
Train on 1 samples
1/1 [==============================] - 0s 136ms/sample - loss: 0.3133
#--- Weights after one pass
Weights: (1, 1) [[1.2689414]]


In [277]:
print(op)
#oo=tf.compat.v1.keras.backend.get_session(op_input_list=())
#op.eval(session=K.get_session())

Tensor("dense_22_1/Identity:0", shape=(None, 1), dtype=float32)


In [211]:
# A Simple Network with predefined weights

model = tf.keras.Sequential()
model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1))
opt=tf.keras.optimizers.SGD(learning_rate=0.5, momentum=0.0, nesterov=False)
model.compile(optimizer=opt, loss='binary_crossentropy')

# ~~~ Set custom weights
wts0=( np.array([[0.5, 0.1], [0.1, 0.5]]),  np.array([0,0]) )
print('Weights(0):' , wts0[0].shape, wts0[1].shape, "\n", wts0[0], wts0[1] )

model.layers[0].set_weights(wts0)
wts01=model.layers[0].get_weights()
print('Weights:' , wts01[0].shape, wts01[1].shape, wts01[0], wts01[1] )

wts1=( np.array([[0.5], [0.5]]),  np.array([0]) )
print('Weights(1):' , wts1[0].shape, wts1[1].shape, "\n", wts1[0], wts1[1] )
model.layers[1].set_weights(wts1)
wts11=model.layers[1].get_weights()
print('Weights:' , wts11[0].shape, wts11[1].shape, wts11[0], wts11[1] )

#--- Do one pass through NN
data=np.array([[1,1]])
y =np.array([1])
f=model.fit(data, y, epochs=1, verbose=1)

print("#--- Weights after one pass");
wts1=model.layers[0].get_weights()
print('Weights:' , wts1[0].shape, wts1[1].shape, wts1[0], wts1[1] )
wts11=model.layers[1].get_weights()
print('Weights:' , wts11[0].shape, wts11[1].shape, wts11[0], wts11[1] )


Weights(0): (2, 2) (2,) 
 [[0.5 0.1]
 [0.1 0.5]] [0 0]
Weights: (2, 2) (2,) [[0.5 0.1]
 [0.1 0.5]] [0. 0.]
Weights(1): (2, 1) (1,) 
 [[0.5]
 [0.5]] [0]
Weights: (2, 1) (1,) [[0.5]
 [0.5]] [0.]
Train on 1 samples
1/1 [==============================] - 0s 153ms/sample - loss: 0.4375
#--- Weights after one pass
Weights: (2, 2) (2,) [[0.5885859 0.1885859]
 [0.1885859 0.5885859]] [0.08858591 0.08858591]
Weights: (2, 1) (1,) [[0.9999999]
 [0.9999999]] [0.7744057]


In [213]:
model.layers[1].output


<tf.Tensor 'dense_3_1/Identity:0' shape=(None, 1) dtype=float32>

In [11]:
dataset = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n_input = 2
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=3)
print(f'Samples: {len(generator)}, Shape:{generator[0][0].shape}')
for i in range(len(generator)):
    x, y = generator[i]
    print(f'{x} => {y}')

Samples: 3, Shape:(3, 2)
[[1 2]
 [2 3]
 [3 4]] => [3 4 5]
[[4 5]
 [5 6]
 [6 7]] => [6 7 8]
[[7 8]
 [8 9]] => [ 9 10]


In [15]:
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=8)

model = Sequential()
model.add(Dense(5, activation='relu', input_dim=n_input))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit_generator(generator, steps_per_epoch=1, epochs=100, verbose=0)
x_input = array([9, 10]).reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[11.77727]]


In [143]:
# A Simple Network with predefined weights

model = Sequential()
model.add(Dense(2, activation='relu', input_dim=2))
model.add(Dense(1))
model.compile(optimizer='sgd', loss='mse')

# ~~~ Set custom weights
wts0=( np.array([[0.5, 0.1], [0.1, 0.2]]),  np.array([0,0]) )
print('Weights(0):' , wts0[0].shape, wts0[1].shape, "\n", wts0[0], wts0[1] )

model.layers[0].set_weights(wts0)
wts01=model.layers[0].get_weights()
print('Weights:' , wts01[0].shape, wts01[1].shape, wts01[0], wts01[1] )

wts1=( np.array([[0.5], [0.5]]),  np.array([0]) )
print('Weights(1):' , wts1[0].shape, wts1[1].shape, "\n", wts1[0], wts1[1] )
model.layers[1].set_weights(wts1)
wts11=model.layers[1].get_weights()
print('Weights:' , wts11[0].shape, wts11[1].shape, wts11[0], wts11[1] )

#--- Do one pass through NN
data=np.array([[1,1]])
model.fit(data, [1], epochs=1, verbose=1)

wts1=model.layers[0].get_weights()
print('Weights:' , wts1[0].shape, wts1[1].shape, wts1[0], wts1[1] )


Weights(0): (2, 2) (2,) 
 [[0.5 0.1]
 [0.1 0.2]] [0 0]
Weights: (2, 2) (2,) [[0.5 0.1]
 [0.1 0.2]] [0. 0.]
Weights(1): (2, 1) (1,) 
 [[0.5]
 [0.5]] [0]
Weights: (2, 1) (1,) [[0.5]
 [0.5]] [0.]
Epoch 1/1
1/1 [==============================] - 0s 32ms/step - loss: 0.3025
Weights: (2, 2) (2,) [[0.5055 0.1055]
 [0.1055 0.2055]] [0.0055 0.0055]


In [126]:
wts01=model.layers[1].get_weights()
print('Weights:' , wts01[0].shape, wts01[1].shape, wts01[0], wts01[1] )


Weights: (2, 1) (1,) [[ 0.43578127]
 [-1.075966  ]] [0.02141919]
